# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ $default-branch, dev ]
  pull_request:
    branches: [ $default-branch, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: List files in the repository
      run: ls 
    - name: List files in the back repository
      run: |
        cd back
        ls 
    - name: Build with Maven
      run: |
        cd back
        mvn -B package --file pom.xml

    - name: Jacoco test report
      run: |
        cd back
        mvn test --file pom.xml

    - name: Upload Jacoco report to artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: back/target/site/jacoco
